# Generated by Django 3.2.7 on 2021-10-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noties', '0002_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
    ]
